### ISSUE TITLE
Can this be made to build/operate with a Windows Store app?

### ISSUE THREAD

**Issue by JamesWHurst** [zeromq/netmq#105]
I see that there is a _lot_ of incompatibilities within this code, with the API that's available for a Windows Store app, or to take advantage of the Windows 8 / Server 2012 platforms. Is this something that anyone has plans to tend to, or does anyone else have an immediate need to use NetMQ on this platform?  Or, is there any specific reason that it would not be appropo for the Win8 or WinRT platform?

**Comment by FaisalZ** [comment]
May I ask how far the progress on making netMQ ready for Windows Store has went up to now?

Thanks,
FaisalZ

**Comment by drewnoakes** [comment]
Hi @FaisalZ. I don't think that there's been any particular progress in this direction.  Have you tested it? Can you point out any particular issues? If you could help in this regard it would be great.

**Comment by FaisalZ** [comment]
I tried to use it within a Windows Store app. But the framework used for Windows Store apps is limited. Not all .Net functionallities are available, or have been replaced into another namespace.
Info about it: https://msdn.microsoft.com/en-us/library/br230302.aspx#networking
Specifically I run into issues with the System.Net.Sockets and System.Net.IPAdress namespace where I get hundreds of Reference Errors telling me things like:
*`System.Net.Sockets.SocketOptionName` doesn't exist in target framework. It is referenced from AsyncIO.dll at AsyncIO.AsyncSocket*
They arise since those namespaces should be replaced by functionallity now available e.g. in the  Windows.Networking.Sockets namespace to make it compatible with Windows Store.
So did somebody already translate those functionallity?

**Comment by FaisalZ** [comment]
@somdoron, after some further testing this seems to be an issue caused by your AsyncIO library deployed with netMQ. Can you help making AsyncIO compatible with Windows Store ".Net Core"?

**Comment by somdoron** [comment]
I will give it a try, little busy for the next two weeks though. From what
you mention it should be simple.

**Comment by somdoron** [comment]
Can you also open an issue on AsyncIO?

**Comment by FaisalZ** [comment]
Done and thanks, for your immediate response.

**Comment by JamesWHurst** [comment]
I had started on that (Windows Store compatibility) last year, and it really does merit substantial work. A *lot* of the .NET Framework is unavailable, and the substituted APIs from the RT are sufficiently different that a major rework would be needed.

**Comment by somdoron** [comment]
I think the best solution is to create simple ZMTP implementation that is PCL and/or Windows store compatible.

It will be client only and will not be very performance.

We can have it as a separate github project (ZMTP.NET?) or inside NetMQ project.

what do you think?

**Comment by JamesWHurst** [comment]
You say a "simple" ZMTP implementation?  Do you mean not implement most of the functionality of ZeroMQ?
I am wondering whether the Windows10 common platform, will be substantially different in what it provides for this type of functionality. Has anyone looked at it (I believe some tech doc is already available)?  Clearly at this point (Win8, 8.1) only client machines are the target, and I assume Windows Server future editions will almost certainly support .NET form for a substantial time.

**Comment by FaisalZ** [comment]
From what I saw in the .Net Documentation for Windows Store Apps, the functionallity is available but moved to another namespace (the Windows.Networking namespace) and the API was changed (so no simple namespace replacement possible).
This Windows.Networking namespace is already a common namespace for Windows 8 and above, including Windows Store & Phone. May be it would be an idea to move to its functionality instead of sticking to the System.Net namespace to be future-proof?

**Comment by somdoron** [comment]
The library lack a lot of features required for netmq. We can make a lean
version just for clients...

**Comment by FaisalZ** [comment]
So how do you define a client version of netMQ? Will it only be able to
receive messages?

2015-03-10 11:41 GMT+01:00 Doron Somech <notifications@github.com>:

**Comment by JamesWHurst** [comment]
I for one am definitely going to NEED messaging capability for the Windows-10 version of my software projects, and if NetMQ cannot serve then I'll have to use something else such as SignalR or whatever. I  almost want to jump in and help create this, but just doing the XML-doc has sucked a massive amount of time, and there is yet gobs of code that I don't have familiarity with. But, yes - clearly it would need to be a separate Visual Studio project, but with the same syntax for the API itself. Otherwise, I think this project (NetMQ) is destined to start to diminish in significance over the next few years. Which I don't want to happen.

**Comment by JamesWHurst** [comment]
I'm starting to tinker with a PCL (Portable Class Library) version of NetMQ.  Q: Has anyone else done anything in this direction yet?  I do *not* want to duplicate anyone else's work!   I was a little hesitant to proceed in-depth, until having Drew Noakes' new API for the Send/Receive methods.

**Comment by somdoron** [comment]
James I'm actually working on something now... I will have a demo running
today and add to github.

Do you think it should be another repository or part of NetMQ?

**Comment by somdoron** [comment]
@JamesWHurst @FaisalZ take a look at https://github.com/somdoron/ZMTP.NET

It is very early, following are some comments:
* Only dealer is implemented
* More is not supported yet
* It is thread safe
* Only Windows8.1 and windows phone at the moment
* Connect only (no bind)
* Does not handle any socket errors like disconnection 
* Can connect to one socket at the moment

**Comment by JamesWHurst** [comment]
Excellent!  I'd like to see it be part of NetMQ, - I guess for emotional reasons since we're working hard to make it totally great. That you're expanding it to cover the need for a PCL, makes it greater in importance.

**Comment by fabsenet** [comment]
what is the state of affairs currently?

I am running windows 10 iot core on a rasperry pi and want to do some messaging but netmq is not compatible with it? did I do something wrong?

```
Installing AsyncIO 0.1.17.
Installing NetMQ 3.3.2.1.
NetMQ 3.3.2.1 is not compatible with UAP,Version=v10.0.
AsyncIO 0.1.17 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
NetMQ 3.3.2.1 is not compatible with UAP,Version=v10.0 (win10-arm).
AsyncIO 0.1.17 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
NetMQ 3.3.2.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
AsyncIO 0.1.17 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
NetMQ 3.3.2.1 is not compatible with UAP,Version=v10.0 (win10-x86).
AsyncIO 0.1.17 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
NetMQ 3.3.2.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
AsyncIO 0.1.17 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
NetMQ 3.3.2.1 is not compatible with UAP,Version=v10.0 (win10-x64).
AsyncIO 0.1.17 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
NetMQ 3.3.2.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
AsyncIO 0.1.17 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
```

**Comment by somdoron** [comment]
Windows phone is not supporting dot net sockets library, so NetMQ cannot be
used. I have started working on zmtp.net as an alternative for clients but
it is not yet completed. You can take a look here:

https://github.com/somdoron/zmtp.net

**Comment by fabsenet** [comment]
So I spent the last hours looking at AsyncIO and NetMQ and ZMTP.net and what can I say, you did your best.

My personal target was to check portability to UWP (Windows 10 Store / IoT Core) and I am really disappointed of Microsoft. Sure, I can understand they want to leave some legacy stuff behind, but the basic networking stuff? Really?

I started with the unity version of the AsyncIO lib and tried to put everything into a UWP class library and there is simply no socket. The only thing I found after digging was the StreamSocket and that was what you tried as well with your ZMTP.net spinoff.

So I played with ZMTP. At first I ported everything from Windows 8.1 to Win10 UWP and the example "just works". I guess, it would be possible to design my client with only one dealer socket.

BUT and there always is a but :-( 
... the basic zeromq semantics are not implemented! 
Start the client before the server => Exception! 
Close the server while the client waits for another msg => Exception!

The Q-Part from ZeroMQ is missing and I guess, one had to copy every little bit of it.

The best way in my opinion to go further would be to implement a third socket abstraction in AsyncIO which uses a StreamSocket under the covers. But we would have to at least change the interface of the AsyncSocket, because UWP does not even have the enums SocketOptionLevel and SocketOptionName. The new socket would simply not support binding and everything else could be possible. I am not sure what other parts in NetMQ itself would not support UWP as well.

**Comment by somdoron** [comment]
Thanks Fabian. I share your thoughts about Microsoft.

I actually think the best solution is ZMTP.NET, we don't to implement
everything and only start with what you need.
The reason I stopped working on ZMTP was because at the time there was no
real need.
Anyway I can help make ZMTP ready for your need, we can start slowly and
eventually make it portable zeromq client.
We don't need all the features of NetMQ and even not the performance of
NetMQ.

Let me know what you think and what you need from the ZMTP.NET library.

Doron

**Comment by fabsenet** [comment]
Hi Doron,

I wrote about the situation in generel on my blog https://fabse.net/blog/2015/10/21/no-messaging-on-windows-10-iot-core/

I am currently thinking about how to invest my time. Because on the one hand side, I like zeroMQ and I think it would benefit from a working UWP port on the other hand, I am thinking to just switch to raspbian on the pi to get things working because my personal target is not to port zeromq but to control that damn LED from my phone :)

I did not decided yet which road to go and I am currently occupied in woodworking project anyway.

Did you hear from others a generel demand for a UWP solution?

**Comment by ruttopia** [comment]
Fabian,

I too am in need for a good messaging library for UWP (Windows IoT).  Did you find any other solution?  I wanted to use ZeroMQ as well and am very disappointed that I can't.  I'm considering SignalR, but am worried about lack of updates to it.

Thanks!
Mike

**Comment by fabsenet** [comment]
Hi Mike,

it is kind of a bad situation. I was once going the signalr route before on uwp / win10 iot on rpi2. It somehow works until it stops working. I filed a concrete issue which maybe got fixed (https://github.com/SignalR/SignalR/issues/3576). The current state of uwp regarding networking in my words is *broken*. I switched to raspbian for my rpi2 client and used a python3 client. (see https://github.com/fabsenet/HomeControl/blob/zeromq/IotPyActor/IotPyActor/client.py) it is not much more than a proof of concept for now but it works.

What I not tried but what maybe is another option is using mono on raspbian and sticking to normal .net.

If you like, you can let me/us know, how you are going to proceed.

Good luck :)

Fabian

**Comment by ruttopia** [comment]
Thanks for all the info - appreciate it!  I am currently looking into AllJoyn since it is built into Windows under the Windows.Devices.AllJoyn namespace and _might_ give me the functionality I need for my scenario...

**Comment by somdoron** [comment]
I can make ZMTP.NET production ready, depends on what you need. Send me an
email if you are interested.

**Comment by bbdb68** [comment]
Hi all

anything new on this subject ? I will soon have to make a communication between my ZeroMQ server and an UWP device, and ZMTP.NET seems to be a possible path. Doron, are you still ok with developping ZMTP.NET ? I wish I could help but I do not know enough about the ZMQ internals.
Otherwise what could be my options : 
  *  raw tcp with a STREAM socket on server side ?
  * websockets ? something completely different ?

Being limited to be a client is not an issue for this project, but good pub/sub performances would be usefull.

Thanks

Bruno

**Comment by somdoron** [comment]
@bbdb68 I don't think you need to know much, I already implemented the wire procotol, you just need to add PUB or SUB patterns, should be pretty easy. I also suggest you take control over the project. I didn't know much about zeroMQ when started NetMQ :-)

**Comment by bbdb68** [comment]
Hi @somdoron 

I propose to start by working on a PR for the SUB pattern, if you are ok to review it. Then I will know more to decide about taking control over the project ;-)

**Comment by rooi** [comment]
Hi @bbdb68 @somdoron,

I would like to use a netmq client in UWP as well. Did you make any progress?

Thanks!

**Comment by bbdb68** [comment]
Hello

I finally went another direction, and I am compiling native ZeroMQ + czmq instead of using the C# stack.
I then use a thin P/Invoke layer for my needs.

This choice is related to Unity : since it uses a very old version of mono, although netmq works smoothly,
performances are cut by a factor 2 compared to native zmq or netmq running outside unity. (this is true for unity on win32, probably not on unity on uwp...). So I finally use the same stack on uwp.

My patches for zmq (c++) and czmq are on my forks of libzmq and cmzq
https://github.com/bbdb68/czmq/tree/uwp
https://github.com/bbdb68/libzmq/tree/uwp

this is far from being PR ready but it works (except socket binding and security)

That said, I saw on nuget that netmq is compatible with .net Core, and that .net core apps should run on uwp... but it seems it does not. .net platforms are a nightmare.... maybe @somdoron can say more about this.

hope this helps.

**Comment by rooi** [comment]
Thanks for your reply and help @bbdb68 !

I gave up the netmq approach for to connect the uwp app directly and used a bridge in between. Not the optimal solution, but it works for now. Hopefully the uwp platform will improve with respect to these libraries.

**Comment by southie** [comment]
I was able to get NetMQ and AsyncIO to work with a UWP application (on the HoloLens).  I am going to end up moving to C++ because of difficulties working with C# .Net Native compiler on my project, but I thought I would give some input on how I got it to work.  Maybe it will be helpful for others going down this path.

I was able to compile AsyncIO and NetMQ for .Net Standard 1.3 with few modifications. This was convenient for me because I wanted to try to keep the communications on the device to be as similar as possible to the desktop application. If you wanted to target UWP specifically, you could add ``|| WINDOWS_UWP`` everywhere a ``#if NETSTANDARD1_3 `` is used.

UWP doesn't support Thread, but NetMQ uses only a few methods that appear to map fairly easily to Tasks. I removed the System.Threading dependency and added a Thread implementation to avoid impacting the existing code.  I was planning on making an Async/Await fork of NetMQ but that is tabled for now.

The only quirk I found in AsyncIO is that on UWP, when compiled with the native compiler, Socket.Connect often returns success on connect, which behaves like IOPending. I only encountered it on connect, but I assume it is possible for any of the socket operations. 

I have the changes checked in to my forks for both NetMQ and AsyncIO under UWP branches.  I was able to get both working with IOCP or native sockets, and I'll put some snippets below for ease of reference.  I wasn't sure how to best condition the changes to the code, so I haven't made any pull requests. 

AsyncIO/Windows/Socket.cs:476
```
if (socketError != SocketError.IOPending && socketError != SocketError.Success)
{
     throw new SocketException((int)socketError);
}
```
NetMQ/UWPExtensions.cs
```
#if NETSTANDARD1_3 || WINDOWS_UWP
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
namespace NetMQ
{
    public class Thread
    {
        public string Name;
        public bool IsBackground = false;
        Task task;
        Action action;
        public Thread(Action a)
        {
            action = a;
        }
        public void Start()
        {
            task = Task.Run(action);
            if(!IsBackground)
            {
                Join();
            }
        }

        public void Join()
        {
            task.Wait();
        }

        public static void Sleep(int millis)
        {
            Task.Delay(millis).Wait();
        }
    }
}
#endif
```

**Comment by somdoron** [comment]
Why not making a Pull request?

**Comment by somdoron** [comment]
Great news by the way

**Comment by southie** [comment]
I have all of my projects based off of Net Standard 1.3.  The current Net Standard 1.3 implementation uses System.Threading to handle the threading.  I had a lot of problems trying to make a target framework for UWP and getting it to work with NuGet for my project (which could be my lack of experience with multi platform build / NuGet).  I didn't want to possibly break the Net Standard 1.3 target by moving them wholesale over to UWP threading Task shim.

**Comment by mqudsi** [comment]
I believe #670 (which is now merged into master) has addressed this in full and this issue can be closed. If not, please comment.
