### ISSUE TITLE
Please sign the NetMQ.dll with a Strong Name

### ISSUE THREAD

**Issue by ghost** [zeromq/netmq#109]
Please sign the NetMQ.dll with a Strong Name.  I'm downloading it via NuGet.

  <package id="NetMQ" version="3.3.0.8" targetFramework="net40" />

**Comment by ashic** [comment]
This effectively breaks any non-SN package that takes NetMQ as a dependency. Example:

Nuget pkg A uses NetMQ 3..3.0.8 (non SN). Applications use this.
Application updates NetMQ to latest 3.3.2.0. (SN). Binding redirects don't work as public key tokens don't match.
Result: Any library using 3.3.0.8 is broken for clients if they update NetMQ.

As updates are broken, this is effectively a breaking change, and would constitute a bump to 4.0.

Are there any workarounds other than modifying ANY library using NetMQ to use a SN version? [Can't think of any.]

**Comment by somdoron** [comment]
Why to bump to 4.0? NetMQ have 3.5 version.

I can think of two solutions:

* Compiling from source without the sn
* Have different distribution which is not using the sn

What do you think?

**Comment by ashic** [comment]
Different distro might be the better approach. In that case, the "NetMQ" one should be non-SN with the SN version having a separate name. The reason is simple...if any lib has been built with pre-SN version, and an app uses the lib, and it updates NetMQ to "compatible 3.3.2" version, it'll stop working. The update path is essentially broken via NuGet. With a separate SN version, it's a concious decision to use that version. Non-SN to SN update will NOT work via NuGet update (i.e. it can't ber resolved even via redirects AFAIK), and to keep NuGet update as an option, the current (i.e. 3.3.08 and its successors) should remain non-SN.

Providing a separate SN version is a pain, but I think some other projects have gone that route.

**Comment by ashic** [comment]
Just blogged: http://www.heartysoft.com/ashic/blog/2015/9/dont-strong-name-existing-nuget-packages . The point is - to .NET, a new public key means a completely separate entity. As such, a package with a new public key shouldn't be SemVer compatible (or it could be argued - even in the same package).
