### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by reiroldan** [zeromq/netmq#13]
For public methods/properties/events we should resort to the .net documenting convention of :

/// \<summary>
/// The comment 
/// \</summary>
/// \<param name="obj">Use for something\</param>
/// \<returns>The return is blah\</returns>

Private methods don't need to be documented this way. Private fields/properties/events can be commented as with simple comments.

Just a suggestion. 

Thoughts?

**Comment by JamesWHurst** [comment]
I'm currently adding extensive comments to the API, for those areas whose operation is evident from the source-code to a non-expert in NetMQ as I am (not).  (boy did that come out awkward!).  I am thinking that as this gets merged in, I can then run it through SandCastle, to generate a Windows help-file for it. 
I've already put over 48 hrs straight. There's a bit of code here - and some major changes since the last time I went through it over a year ago.
