### ISSUE TITLE
Should Msg be finalizable?

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#267]
If a message is not closed then it won't return its buffer to the `BufferManager`, nor will it decrement its internal atomic counter.

This seems only to matter for pooled messages however.

How often are non-pooled messages used? Requiring this type to be tracked by the GC for finalization could really hurt performance, but if might increase correctness if pooling code forgets to close the messages.

Is there some other way we would know that message buffers are not being released properly? If so, then maybe the code should be left as-is.

**Comment by somdoron** [comment]
Pooled messages are only used if you enable buffer pooling which improve the memory by reduce garbage collection work but actually reduce the throughput of messages (because the BufferManager of .net is not very efficient, custom buffer manager might solve that). Anyway correct management of Msg object is very important so adding finalizer will just hide the fact that we have a bug. Msg is also expose in the API but rarely used (you should use it if you really want zero-copy and zero-allocations and know what you are doing).

**Comment by drewnoakes** [comment]
I suppose a buffer manager implementation should be able to detect if Msg instances are not being released to the pool.
