### ISSUE TITLE
Hiding the NetMQ.zmq namespace from users

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#299]
There are still a few public types in the `NetMQ.zmq` namespace. From the user's perspective, there's no clear reason for this namespace and it offers the potential for confusion.

Currently the only non-internal types in this namespace are:

* `Endianness`
* `PollEvents`
* `SendReceiveOptions`
* `SocketEvent`
* `ZmqSocketType`
* `ZmqSocketOptions` (though #298 makes this internal)

Can we move these to the `NetMQ` namespace?

Unless user code explicitly qualifies these types in their code, this wouldn't be a breaking change. 

If all public types are moved out of the `NetMQ.zmq` namespace, I think we'll have to create an unused type in that namespace so that users don't receive compiler errors on the directive:

```csharp
using NetMQ.zmq;
```

That type could just be:

```csharp
namespace NetMQ.zmq
{
    [Obsolete("Don't use this type!")]
    public static class ThisNamespaceIsNotUsed {}
}
```

Does this seem like a good idea?

**Comment by JamesWHurst** [comment]
I agree.  But since this may mandate changes to developer-code, should it not be wrapped into the next code-breaking change (even if that change is totally trivial), in keeping with the principles of Semantic Versioning?   And if so, then there's probably no need to actually have the dummy-namespace still around, since (in the general case) textual edits will be needed to the user's code.
Regardless - I do think it's cleaner to just have the one namespace.

**Comment by somdoron** [comment]
I think it is a good idea, and then we can get rid of the zmq folder at all and change it to something like Core.
