### ISSUE TITLE
Socket outgoing API

### ISSUE THREAD

**Issue by leverate-somech** [zeromq/netmq#340]
I want to make the socket outgoing api consistent with receiving API changes from #275.

What do you think should be the naming of the methods?

I thought of:

SendMoreFrame - for a more frame?
SendLastFrame - for last one?

We can also make it a fluent API like

Socket.Frame("123").Frame(new byte[]{0}).Send();

and the non blocking way

Socket.Frame("123").Frame(new byte[]{0}).TrySend();

However as much fluent is cool it also allocate more memory which mean performance penalty.

**Comment by leverate-somech** [comment]
I just don't want to multiple each method by 3 (More, Last and one with more parameter)

**Comment by drewnoakes** [comment]
Current sending API of `IOutgoingSocket` is:

    void Send(ref Msg msg, SendReceiveOptions options)

With extension methods:

    byte[] bytes = ...;
    socket.Send(bytes)
    socket.Send(bytes, length, dontWait=false, sendMore=false)
    socket.Send(bytes, length, SendReceiveOptions)
    socket.SendMore(bytes, dontWait=false)
    socket.SendMore(bytes, length, dontWait=false)

    string str = ...;
    socket.Send(str, dontWait=false, sendMore=false)
    socket.Send(str, Encoding, dontWait=false, sendMore=false)
    socket.Send(str, Encoding, SendReceiveOptions)
    socket.SendMore(str, dontWait=false)
    socket.SendMore(str, Encoding, dontWait=false)

    NetMQMessage msg = ...;
    socket.SendMessage(msg, dontWait=false)

---

Some initial thoughts on how we can simplify this:

- use the `Try*` pattern to signify non-blocking calls (`dontWait=true`)
- obsolete usage of `SendReceiveOptions`
- use the `HasMore` flag of `Msg` (on `IOutgoingSocket` at least) 

If we are to follow a similar approach to that of #275 then `IOutgoingSocket` could be modified to:

    void TrySend(ref Msg msg, TimeSpan timeout)

As with receiving messages, blocking send operations pass a negative (infinite) timeout to `TrySend`.

---

Generally I don't like fluent APIs, but this might actually be a good fit. Certainly it would be easy to reason about as a user of NetMQ. The concept of blocking/non-blocking and last-frame is taken care of. Would there be extra memory pressure beyond a single heap allocation of `List<byte[]>`?

How about:

    socket.CreateOutgoingMessage()
        .Add(new byte[] { 1, 2, 3, 4 })
        .Add(msg, Encoding.ASCII)
        .Send();

The first method returns a `struct OutgoingMessage` which wraps a reference to the socket and a `List<byte[]>`. It has `Send`, `TrySend(timeout)` and `Add(byte[])`. Other overloads of `Add` are extension methods that create and add `byte[]`. In fact, `CreateOutgoingMessage` could be an extension method itself.

There is some overhead here, but perhaps we can make the `NetMQMessage` scenario more optimal for performance critical sends.

Not directly on-topic, but maybe the `OutgoingMessage.Send`/`TrySend` functions could lock internally for thread safety on the socket.

**Comment by leverate-somech** [comment]
I like the TrySend idea, mainly because it is following the TryReceive. Regarding the fluent, I have a mixed feeling about that do. Anyway I think the TrySend should replace the Send methods and for NetMQMessage we can replace it with fluent.

Regarding locking, I planning to port the Server & Client socket types from libzmq which provide thread safety.

Lock around a send will only work for single frame protocols, for multipart it can cause a lot of problems. Also what about receive? when you lock around receive and there is no messages and then you lock around send you will never be able to send until a message is received.

Using different locks for send and receive is not possible without internal refactoring, which is what the Server and Clients sockets types do (prevent multimessage and use Conditional Variable).

**Comment by drewnoakes** [comment]
Regarding locking, I was referring to `OutgoingMessage.Send` (from the proposed fluent API), not `IOutgoingSocket.TrySend`. It could be threadsafe for applications that only send via that function, as all frames of the message are available at the moment the send occurs. However if any of the sends fail, it's not clear what to do.

Porting the new Client/Server socket types would be great and is probably a better idea overall anyway.

So, ignoring locking, I think this is pretty close to a workable API. We could obsolete pretty much all the `IOutgoingSocket` extension methods if we use the fluent API. Otherwise we need complex overloads to signify last frames and blocking/non-blocking on a per-frame basis. Wrapping this all up in a single atomic `Send`/`TrySend` over one or more frames seems nicest.

**Comment by somdoron** [comment]
and what about the inconsistency with the receiving API? one is fluent and the other is not...

Can we do fluent to Receive API somehow?

**Comment by drewnoakes** [comment]
Interesting. I'm not sure the receiving APIs make sense in fluent form
though as there would be potentially multiple return values. How would you
imagine that looking?

They would still be more consistent than they are now. Perhaps we can do
even better.

**Comment by somdoron** [comment]
the receiving can be with lambda, something like:

socket.CreateIncomingMessage().ReceiveString(s=> name = s).ReceiveBytes(b => bytes = b);

We can also have an optional flag, which mean this is the last mandatory frame, from here it is optional (will not through exception is missing), like:

socket.CreateIncomingMessage().
  ReceiveString(s=> name = s).
  Optional.ReceivePayload(b => bytes = b);

**Comment by somdoron** [comment]
But I'm we might start with making the existing Send API look more like the Receive API. Then we can continue with creating fluent API for both.

By the way, the fluent API doesn't have to start from the socket, we can start it from object the can be reused, like:

OutgoingMessage outgoing = OutgoingMessage.Create();
outgoing.Add(name).Add(Payload).Send(socket); // send is also clearing the existing message

Anyway I think when using fluent we should not use an list but instead to compose the parts like linked list, like:

```csharp
class OutgoingFrame
{
  OutgoingFrame m_next;
  byte[] m_bytes;

  OutgoingFrame(byte[] bytes) 
  {
    m_bytes = bytes;
  }

  public void Send(IOutgoingSocket socket)
  {
    SendInternal(socket, false); 
  }

  void SendInternal(IOutgoingSocket socket, bool more)
  {
    if (m_next != null)
      m_next.SendInternal(socket, true);
  
    socket.Send(bytes, true);
  }
}
```csharp

**Comment by drewnoakes** [comment]
One benefit of your code is that you can treat the intermediary objects as immutable. For example, you could reuse a leading set of frames:

```csharp
var headers = new OutgoingMessage().Add(...).Add(...);

headers.Add(body1).Send(socket);
headers.Add(body2).Send(socket);
```

A downside of this is that the following code looks reasonable but actually doesn't work:

```csharp
var headers = new OutgoingMessage();
headers.Add(...); // returns a value which is ignored
headers.Add(...);
```

You can use the `[Pure]` annotation to get R# to provide a diagnostic for this, but that's hardly a solution.

A linked list also uses O(N) allocations instead of O(1).

(BTW I think the `more` param in `SendInternal` should be used on the last line?)

I'm not convinced by the fluent APIs in general though. If someone really wants the above behaviour, it's not hard to add the code yourself based on a good `IOutgoingSocket` interface.

Whatever design we create at the lowest public API level should be as minimal as possible, both in terms of complexity and resource usage (which is primarily allocations I guess).

Multipart messages really do make the whole API much more complex :)

So is a good place to start just to refactor `IOutgoingSocket` to obsolete the current `Send` and use `bool TrySend(ref Msg msg, TimeSpan timeout)` instead? Can we also use the `HasMore` property on `Msg`? Currently it's read only.

**Comment by drewnoakes** [comment]
I missed your comment about fluent receive using lambdas.

It's a clever approach, but I'm not sure it'd be easy to discover. Also each of those lambdas involves an object instantiation, so receiving now allocates/collect O(N) in the number of fields.

**Comment by somdoron** [comment]
I'm with out , I think we should forget from the fluent from now and make the send consistent with the send. I actually had it ready but I undo it as I don't like the number of overloading. I will get to it again :-)

**Comment by somdoron** [comment]
I started working on it:
https://github.com/somdoron/netmq/tree/SendAPI

**Comment by drewnoakes** [comment]
Reading through the diff, it looks great. Minor typo in classname of `SendReceiveConstans`. Wonder if there's a shorter way of specifying an infinite timeout. Shame that .NET's `Timeout.Infinite` is an `int`, not a `TimeSpan`.

**Comment by leverate-somech** [comment]
So I'm thinking now on the extension methods,

Option 1:

```
public static void SendFrame([NotNull] this IOutgoingSocket socket, byte[] bytes, bool more = false);
public static IOutgoingSocket SendMoreFrame([NotNull] this IOutgoingSocket socket, byte[] bytes)
```

Option 2:
```
public static void SendFrame([NotNull] this IOutgoingSocket socket, byte[] bytes, bool more);
public static void SendLastFrame([NotNull] this IOutgoingSocket socket, byte[] bytes);
public static IOutgoingSocket SendAnotherFrame([NotNull] this IOutgoingSocket socket, byte[] bytes)
```

What do you think?

**Comment by drewnoakes** [comment]
Another option:

    socket.AddFrame(...).AddFrame(...).AddFrameAndSend(...);
