### ISSUE TITLE
Use of EventDelegatorHelper<T>

### ISSUE THREAD

**Issue by drewnoakes** [zeromq/netmq#344]
Just looking at this class, I can't see what it gives above just using a C# `event` (`MulticastDelegate`) directly. Am I missing something?

Also the code here looks suspicious:

* [NetMQActor constructor](https://github.com/zeromq/netmq/blob/master/src/NetMQ/NetMQActor.cs#L140)
* [Actor constructor](https://github.com/zeromq/netmq/blob/master/src/NetMQ/InProcActors/Actor.cs#L68) (deprecated)

Shouldn't the `unregisterFromEvent` actions be using `-=` instead of `+=`? Also, then 'send' variant uses different events in the register vs unregister actions.

I've looked at this for a while and can't work out if it's by design. If so, let's document it. If not, I'll get a PR together.

**Comment by somdoron** [comment]
you are right about the bug in the code. We want to delegate an event from the NetMQSocket to the NetMQActor, however we only want to register once if anyone register to the NetMQActor and to unregister if not one register.

It is very small performance improvement (that might not needed, as usually only one register happen anyway), so if would not use it we would register to the origin event the number of times the event is register and we will create events args multiple times instead of once.

When coming to think of it, the improvement is very small and this only complicated the code. I'm ok with removing it.
