### ISSUE TITLE
Sync with 0MQ progress?

### ISSUE THREAD

**Issue by georgiosd** [zeromq/netmq#355]
Hi!

Thanks for making a native 0MQ implementation, truly a worthy endeavor! 

I'm particularly interested in the authentication piece and saw that 0MQ 4.x has a native solution but NetMQ hasn't caught up yet. 

Have you got any plans/ETA to sync up?

Also, is it possible to apply your current security model with pub/sub? Please post some sample code if possible. Mainly interested in allowing the server to authenticate the subscribers.

Thanks again.

Georgios

**Comment by somdoron** [comment]
Hi Georgios,

Currently there is no plan to catch up with zeromq security and ZMTP v3.0.
However if you want to invest time in it I can help and guide you on how to
do that.

**Comment by georgiosd** [comment]
Go ahead, I'll do my best!

Please let me know where I can find the final spec and where you think the changes should go in the code.

**Comment by somdoron** [comment]
So I would start with supporting ZMTP v3.0 with null encryption and
authentication, the main file you need to work with is

https://github.com/zeromq/netmq/blob/master/src/NetMQ/Core/Transports/StreamEngine.cs

You can read the RFC here:
http://rfc.zeromq.org/spec:23

The follow commits from libzmq is preparation to the zmtp v3.0, I suggest
to start with them:
https://github.com/zeromq/libzmq/commit/7942db7606c76f71b77863f8f883047ec69ffc5f
https://github.com/zeromq/libzmq/commit/9d79ac283061c1531c1ab2878a2765afdaba9d77

The implementation of Null mechanism:
https://github.com/zeromq/libzmq/commit/cd4d8bb15a18831e1f4d45f2c5bee11d0c30b436
https://github.com/zeromq/libzmq/commit/a7032e9ca8a75fea4c599c51dd9fce5e9ca7c9f3
https://github.com/zeromq/libzmq/commit/d47295db708cb19a46070bc5f88d76d117abc339

Please note that the Stream Engine of NetMQ is working differently then the
one of libzmq because the use of IOCP vs Reactor, you can read more about
the difference here:

http://somdoron.com/2014/11/netmq-iocp/

**Comment by jameswm** [comment]
In the meantime, has there been any interop testing with zmq 4.x? That is, if I have a 4.x endpoint, and it's not using new 4.x features, will it interop with another endpoint built on the latest NetMQ?

**Comment by somdoron** [comment]
Yes. Zeromq will downgrade to zmtp v2.0. Tested and in production use

**Comment by wavelet4775** [comment]
NetMQ operation with zmq 4.x?  I am attempting to use NetMQ with a zmq 4.x endpoint and I seem to be having connection issues.  I am testing with a REQ/REP pattern where zmq 4.4 is the REP server and  NetMQ is the REQ side.  With NetMQ version 3.3.09 the connection works find and I can get messages back and forth.  If I upgrade to NetMQ version 3.3.2.2 or the newer NetMQ4 the connection fails.  I believe the connection to the zmq 4.x server is not made properly because if I watch with WireShark on the NetMQ client side, messages are never sent to the zmq server side.   I am using a TCP connection to and IP address and port 5555.   Am I missing some set up issue that might be keeping the two sides from connecting?
Thank you for your help... I would really like to use the features in the new NetMQ.

**Comment by somdoron** [comment]
It should work, I guess you are not using curve features?

Can you provide the code for both?

**Comment by wavelet4775** [comment]
My code base is fairly complex, but I have reduced the code for test purposes because of the connection issue.  For the zmq 4.x server side I am running on Ubuntu and I pulled the code sample directly from:  http://zguide.zeromq.org/cpp:hwserver (literally a copy paste).   The connection statements are:

    zmq::context_t context (1);
    zmq::socket_t replySocket (context, ZMQ_REP);
    replySocket.bind ("tcp://192.168.1.104:5555");


For the client .NET side running on Windows, the connection is simply:

        NetMQContext zmqContext = NetMQContext.Create();
        RequestSocket  cmdReqClientSocket = zmqContext.CreateRequestSocket();
         if (cmdReqClientSocket != null)
         {
               cmdReqClientSocket.Connect("tcp://192.168.1.104:5555");
         }
The Send Request Receive Reply are simply:

        byte[] = byteArray = Encoding.ASCII.GetBytes("Hello");
        cmdReqClientSocket.SendFrame(byteArray);
        byte[] rxBytes = cmdReqClientSocket.ReceiveFrameBytes();
        string rxMsg = ASCIIEncoding.ASCII.GetString(rxBytes);

The NetMQ code blocks forever on the ReceiveFrameBytes.  On the zmq 4.x server side the server code replySocket.recv (&requestRx); never receives the transmitted "Hello" message.  Watching with WireShark the the Hello message is never transmitted from the client.   The NetMQ4 version has the same issue as far as I can tell.  If I change to NetMQ version 3.3.0.9 the system works just fine.  The Hello message is transmitted to the server and the server responds with "World".  The data packets can be seen with WireShark as expected.  

Any help you can be with this would be greatly appreciated.
