### ISSUE TITLE
Clear up Strong Named Nuget Stuffz

### ISSUE THREAD

**Issue by ashic** [zeromq/netmq#380]
Creating a new issue, as a discussion on this might be useful. This follows on from https://github.com/zeromq/netmq/issues/109 

The issue is that NetMQ started strong naming since 3.3.0.10 (quoting Som). Now this, as far as SemVer goes, is fully compatible with 3.3.0.8. As such, an app using a library that uses NetMQ can update NetMQ without worrying - only this doesn't work. 3.3.0.8 and 3.3.0.10+ have separate public key tokens, and as such to .NET these are two completely separate assemblies - not versions of the same. As such, even binding redirects can't make the app work. A look into Fusion logs confirms this. This is less an issue for end apps directly using NetMQ, but any libraries using NetMQ will suffer this problem. App developers will need to know that if they use a library built against 3.3.0.8, they can't update NetMQ to 3.3.0.10+ (and update all allows this to accidentally happen). Paket bringing down latest will exasperate the problem (most likely).

I can see three options:
- Communicate the fact that the NetMQ nuget pkg is now strongly named, and as such it's a different assembly (with different pk) published through the same NuGet pkg, and so end app developers will need to be careful when using any library using NetMQ. And library developers should update their libraries to 3.3.0.10+. This takes the least amount of effort from NetMQ's part, but IMO is bad form. Then again, it's OSS. And to date, there's "only" 13K downloads. This is evil, but... :)
- Ask library devs to build from source. This is terrible, beats the purpose of NuGet, harms the eco system, kills kittens, causes acid fog. Realistically, this means any bug fixes for NetMQ can't be leveraged until the library developer updates their package. And library developers will have to ILMerge NetMQ as the end app might use a different version. This - IMO - is the worst option.
- Kill off the 3.3.0.10 - 3.3.2.0 nugets, do another release (3.3.3.0) that's not strongly named. Communicate this so those on recent packages are aware. Release a separate nuget package - NetMQ-SN that's strongly named. This ensures the semantics are preserved, nuget updates work properly, and there's rainbows and clouds everywhere. This does mean some work on part of the NetMQ maintainers. This prevents things that have worked stop working after a "compatible" nuget update.

Here's a blog post outlining the problem further: http://www.heartysoft.com/ashic/blog/2015/9/dont-strong-name-existing-nuget-packages 

Thoughts?

**Comment by somdoron** [comment]
I actually never signing my projects, but that because they are usually internal.

@ashic correct me I'm wrong but changing the project now to be unsigned will actually be a problem to anyone using versions 3.3.0.10 and later because the public key is different.

Also any signed project won't be able to use NetMQ as signed project cannot used unsigned assembly (I'm not sure about this, but that my checks confirm that, maybe there is an option to disable this). 

I actually think we should go with option 1, for the last year since 3.3.0.10 we had no complains. Also versions 3.3.0.10 and 3.3.0.11 have much more downloads than version 3.3.0.8, so I'm assuming most people use version 3.3.0.10 or later.

We might have a different distribution for unsigned, but that it is more overhead when releasing a version, the question is how much of a problem it is for existing project to rebuild there project.

One last comment, I think the security of signed assembly when the private key is public on github is not really a security, so the signed project on nuget is just to make the life of signed assemblies easier.

**Comment by ashic** [comment]
I see your point. I've update my packages to use 3.3.2.1 as the min version. It might be a good idea to have a little section on the homepage (and in the NuGet description) to say that versions prior to 3.3.0.10 shouldn't be used. (I think NuGet also supports removing deprecated packages from the feed?).

**Comment by somdoron** [comment]
Do you want to provide pull request for that? I will remove the old
versions from Nuget.
