### ISSUE TITLE
Disposing socket and linger

### ISSUE THREAD

**Issue by somdoron** [zeromq/netmq#424]
To start, Socket.Dispose is actually async operation which continues in the background, when calling context.Dispose we actually wait for all the background operations to be complete.

Now that we removed the need for context the last socket get disposed is actually clearing the library, therefore it might get block as context get blocked if linger is not zero and still messages to send. This is true only if you are creating socket without context, if you still use the context you get old behavior.

The problem is that it is not intuitive, socket.dispose get blocked because of another socket?
In the past only the context.dispose was getting block.

take a look at following code

``` csharp
            DealerSocket p1 = new DealerSocket();
            DealerSocket p2 = new DealerSocket();
            DealerSocket justSocket = new DealerSocket();

            p2.Options.ReceiveHighWatermark = 10;
            p1.Options.SendHighWatermark = 10;

            p1.Bind("tcp://localhost:55555");
            p2.Connect("tcp://localhost:55555");

            int count = 0;

            p1.SendFrame("echo");

            // we fill the queue
            while (p1.TrySendFrame(TimeSpan.FromSeconds(1), "echo"))
            {
                count++;
            }

            Console.WriteLine("Blocked after {0}", count);

            p1.Dispose(); // this is causing the problem
            p2.Dispose();
            justSocket.Dispose(); // will get blocked
```

Just socket will get blocked, very hard to find.

I already have a fix that will make p1.Dispose to block. However this is breaking change as well. Users which didn't care about disposing the context never cared about this behavior. new version can break code and make dispose get blocked all around application.

Few solution:
1. Forget about cleaning the library (stopping the io thread) ,it is a background thread, just exit the app.
2. Users who care about clearing the library can call Global.Clean() or something.
3. Changing the linger default to zero or 1 second, also break change, however I think is subtle and most users don't know about.
4. When creating library register for AppDomain.CurrentDomain.ProcessExit and clean the library when process exit - the problem is that now someone won't understand why application won't exit, we can make a global property to disable this behavior.

I prefer the 4 solution.

@drewnoakes @ashic what do you think?

**Comment by MikeFair** [comment]
I think something to also consider is how long it has been since the peer endpoints have sent/received any messages (can/is the physical connection up)?

If the messages are successfully being dequeued, then they should finish, or at least run for as long as the linger option allows.  However if the far side is not physically connected and is unresponsive to immediate connection requests, then dump the messages and let the Sockets and Context Dispose themselves.  If this had been the default behavior, having linger enforced only when a physical connection can be made, then I don't think I'd have noticed an infinite linger.

All in all, I think changing the default behavior on application exit, however it's done, is a good idea.  

When a Process does not exit cleanly, it usually gets unceremoniously killed and the whole state machine gets lost anyway. The hope is to deliver as many packets as possible and provide some assurances about what  got delivered and what didn't.  

On the whole though, the connection oriented transports are fairly reliable things when they aren't blocked or misconfigured; so if a message remains in a queue and the remote endpoint is unresponsive, then it's likely that those messages won't ever get delivered and would end being dropped one way or another.  The challenge with linger as it's been defined, is it assumes there's a peer to receive the messages, that the application has the time to wait until the context is finished, and that the messages will eventually complete.  The problem is that more often than not, when a Context gets Disposed with outstanding messages on it, then at least one of those assumptions isn't true and that case should be detected and handled differently.

**Comment by astrowalker** [comment]
@somdoron , just 2 cents, options (1), (2), (4) involve exiting entire application, while the problem is more local -- disposing given socket. So I understand correctly if I do a lot of create/dispose I have resource leak (I am not exiting app) by design.
