### ISSUE TITLE
Make AsyncIO a source dependency?

### ISSUE THREAD

**Issue by buybackoff** [zeromq/netmq#503]
Either via Git submodule or Paket, it is very easy to make AsyncIO a part of NetMQ as source files, not a dll via NuGet. There are minor annoyances when debugging NetMQ, especially with the recent binary versions mismatch. AsyncIO licence is compatible with NetMQ's one - MPL 2.0 is specifically per file, not per project.

**Comment by buybackoff** [comment]
Please have a look at the linked commit above - works seamlessly.

**Comment by somdoron** [comment]
@drewnoakes what do you think?
I like it but I'm not sure it is the best pattern to manage dependency.

**Comment by buybackoff** [comment]
In F#/[Paket](https://fsprojects.github.io/Paket/) world linking source files is becoming the default way to manages dependencies. Git sub-modules do not require any additional tools like Paket... I [use this approach](https://github.com/Spreads/Spreads/tree/master/lib) lately whenever a license permits that, and this greatly reduces debugging complexity, dependency management and F# interactive reference hell.

**Comment by drewnoakes** [comment]
@somdoron I'm not 100% either. The only problem I see at present is that
people upgrade AsyncIO because "newer is better", but in reality the
tooling should only expose NetMQ for upgrades, and take the transitive
dependencies requested by that "root" dependency. This is a problem with
the packages.config and csproj model.

The new project.json and xproj model (from dnx and aspnet core) seems much
better. Users only specify the NetMQ package, and the tooling sorts out the
rest. So if that model were commonplace, I don't think we'd be having this
discussion.

On the other side, Git submodules often confused newcomers who clone
without recursion. I expect we'd start seeing questions about compile
errors due to missing files or out of date submodules.

I've heard people advocate for Git subtrees as an alternative to
submodules, but I find that quite hacky somehow. Not far off copy/paste.

I figure in the next year we will see more people using the project.json
model and this will no longer be an issue.

Ultimately there is nothing wrong right now for people who understand their
tools, and the pattern in place is quite common and reasonable. I like
helping avoid pitfalls, but it seems that unless we copy the code directly
into the NetMQ repository we will just create a different kind of problem
for a different group of users.

**Comment by buybackoff** [comment]
Rebase works smoothly with that commit. So I am now happy with my fork and this is just a general suggestion. Please close this if you do not want to go ahead with it.
