### ISSUE TITLE
Implementation problem with error handling

### ISSUE THREAD

**Issue by cabrinoob** [zeromq/netmq#505]
Hello, I am trying to make something I usually do using clrzmq4 with NetMQ :

public ZMessage Process(CancellationTokenSource cancellor) {
    while (true) {
        var p = ZPollItem.CreateReceiver();
    ZMessage msg;
    ZError error;
    if (socket.PollIn(p, out msg, out error, Heartbeat)) {
        return msg();
    } else if (Equals(error, ZError.ETERM)) {
        cancellor.Cancel();
        break;
    } else if (Equals(error, ZError.EAGAIN) && --Liveness == 0) {
        Thread.Sleep(Reconnect);
        ConnectToBroker();
    }
        ... do something else here and go back to pollin
    }
}
With clrzmq4 the Pollin method of the socket give as an output parameter the error code if it occurs.

How do you do the same thing with NetMQ.

(sorry, I'am a noob ^^)

Many thanks for your precious help

**Comment by somdoron** [comment]
I'm not sure what you are trying to do. If you can explain it will be easier.

Anyway you can use the TryReceive methods, they return false when message is not available (like EAGAIN) and also accept timeout, so it might be everything you are trying to do.

**Comment by cabrinoob** [comment]
Ok, sorry. What I'am trying to do is to adapt some of the patterns found on the zeroMQ guide like the Majordomo or the Paranoïd Pirate. In these patterns I'd like to reuse the Heartbeat approach in the broker but I have some difficulties to adapt the code for error handling.

These samples are using error codes to handle this, but in the NetMQ documentation there nothing about error handling.

How can I handle a shutdown of the broker in the worker code? How can I make the difference between "no response" and a connection failure? When the broker comes back, do I have to reconnect? If yes, how can I manage this? It's very clear in the ZMQ guide, but I can't figure it out with NetMQ.

I think I'am missing something.

Thank you for your help.

**Comment by somdoron** [comment]
So NetMQ is trying to make error handling more like c#. So instead of AGAIN error code you have the Try methods which return false if the message cannot be delivered because of highwatermark reached on no message available (AGAIN Error), for the rest you have NetMQException and it derivatives, like:
* HostUnreachableException  - when mandatory is set on a router and the destination doesn't exist
* InvalidException - for various invalid operations.

You can learn more about exceptions here:
https://github.com/zeromq/netmq/blob/master/src/NetMQ/NetMQException.cs

Regarding no-response vs connection failure, neither NetMQ or zeromq have built-in support for this, this is way you need some of the patterns from the book. In that NetMQ works the same way as ZeroMQ.

So let me summarize how to handle exceptions on NetMQ:
* Use TrySend methods if you want to send with a timeout or don't want to block on sending. This will return false if the high watermark is reached and true it the message was sent.
* Use TryReceive methods if you don't want to wait forever for incoming message, you can use it with timeout. Return true when message is fetched or false if no message is ready.
* HostUnreachableException - when you are using a router with mandatory set to true. thrown when you are sending a message to known identity.

This covers most of the exception handling you need to know about NetMQ. 

I will try to take the piece of code you wrote in the beginning and covert it to NetMQ, although I'm not sure what you tried to do:

```csharp
public NetMQMessage Process(CancellationTokenSource cancellor) 
{
  while (true) 
  {
    NetMQMessage msg;
    try 
    {
      if (socket.TryReceiveMultipartMessage(Hearbeat, ref msg)
        return msg();
      else if (--Liveness == 0)
      {
         // This is like EAGAIN
         Thread.Sleep(Reconnect);
         ConnectToBroker();
      }
    }
    catch (TerminatingException)
    {
      canellor.Cancel();
      break;
    }
    //  .. do something else here and go back to pollin
  }
}

**Comment by cabrinoob** [comment]
Ok, thank you. It's clearer now. I have totally missed the mandatory option with the router.

Thank you
