### ISSUE TITLE
Exact match on Pub/Sub

### ISSUE THREAD

**Issue by buybackoff** [zeromq/netmq#515]
I have realized that often I use only exact matches in pub/sub, without wild cards and prefixes. Also, I remember from NanoMsg "pitch" that their subject matching was "much more efficient" due to using a radix tree vs simple trie in ZeroMQ.

So my question is: did someone profile how expensive is the trie search (e.g. as % of total CPU load) and how much memory it allocates vs a simple dictionary (on loopback and on LAN)? My use case is hundreds to low thousands topics maximum. However, I could easily reach a situation when I have a hundred very hot topics and double-digit Ks of cold topics that consume memory and slow down matching on the hot topics. Should I bother with constructing a benchmark, or network and other parts will always be a bottleneck even on localhost?

Other than performance, I need to use a postfix to distinguish "A" and "AB" subject, e.g. add a vertical pipe: "A|" and "AB|".

We could add an option for this and use a different matching logic when the option is set.

**Comment by somdoron** [comment]
ZeroMQ now have radio/dish pattern which use exact matching.

I like the exact matching, I also think it is pretty easy to add an option to change it to exact matching (both on sub and pub because sub also do filtering).

Regarding performance, I don't know, so far I didn't have any problem with it.

**Comment by buybackoff** [comment]
This is probably a nano-optimization that would only make sense with constrained generics as subjects to avoid boxing. Only makes (if any) sense for IPC.

**Comment by somdoron** [comment]
Actually new zeromq radio-dish pattern is using exact matching.

Also I once tested it for another framework, it is much faster.

One day we will port it to netmq...
On May 4, 2016 21:53, "Victor Baybekov" <notifications@github.com> wrote:

This is probably a nano-optimization that would only make sense with
constrained generics as subjects to avoid boxing. Only makes (if any) sense
for IPC.

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/zeromq/netmq/issues/515#issuecomment-216964599>

**Comment by buybackoff** [comment]
I guess in .NET context more gains would theoretically come from avoiding
boxing/conversion, e.g. Int64 to bytes. My initial thought was that I
allocate like crazy on the hot path just to convert blittable subjects to
`byte[]`.

In native repos we start with pointers, so it is not an issue there.

On May 4, 2016 10:02 PM, "Doron Somech" <notifications@github.com> wrote:
>
> Actually new zeromq radio-dish pattern is using exact matching.
>
> Also I once tested it for another framework, it is much faster.
>
> One day we will port it to netmq...
> On May 4, 2016 21:53, "Victor Baybekov" <notifications@github.com> wrote:
>
> This is probably a nano-optimization that would only make sense with
> constrained generics as subjects to avoid boxing. Only makes (if any)
sense

**Comment by buybackoff** [comment]
Do you think a strongly-typed derived classes of XPub/XSub could be a solution? Or, there could be a different approach, e.g. used by NATS, where they just use an integer to substitute a string subject.

**Comment by somdoron** [comment]
I think it is hard to maintain topics of integers. My opinion is that we should only support strings.

libzmq radio-dish support exact matching on string only.

**Comment by somdoron** [comment]
we can do something specific for netmq, but I think porting radio-dish is better.
