### ISSUE TITLE
Pub Sub Mystery 

### ISSUE THREAD

**Issue by nathvi** [zeromq/netmq#529]
I created a very simple pub console app, and a corresponding sub console app. 

The sub console app subs to "TopicA", and looks like this. 
[Sub.txt](https://github.com/zeromq/netmq/files/228739/Sub.txt)

The pub console app publishes to "TopicA", and looks like this. 
[Pub.txt](https://github.com/zeromq/netmq/files/228754/Pub.txt)

Everything here works fine. If the pub publishes, the sub will get the message. 
Great. 

The problem I'm having, is when I remove the while true loop from the pub app.
I want to just publish once, but the sub app does not get the message when I remove the while true loop from the pub app.
Why is this?

**Comment by somdoron** [comment]
I think it the most famous question with zeromq/netmq :-)

The problem is that you cannot really know when the sub will connect to the publisher, so when you publish you message the subscriber is not yet connected therefore missing the message. In real application you don't really care, if you want reliable pub/sub take a look at the zeromq guide.

For testing you can just put a little sleep after the sub.Connect and before publishing the message

**Comment by nathvi** [comment]
Yes, I saw this was a problem in other posts after I had posted this question. Thank you.
