### ISSUE TITLE
TryReceiveFrameBytes   in .net 4.0 is work good , but  in dotnet core can't receive anything !  

### ISSUE THREAD

**Issue by maikebing** [zeromq/netmq#651]
### Environment

    NetMQ Version: 4.0.0.1   
    Operating System:  Windows 10 , ubuntu 16.04 
    .NET Version:     dotnet core 1.1.1

### Expected behaviour

            using (var server = new ResponseSocket("@tcp://localhost:5556")) // bind
            using (var client = new RequestSocket(">tcp://localhost:5556"))  // connect
            {
                // Send a message from the client socket
                client.TrySendFrame(System.Text.Encoding.UTF8.GetBytes( "Hello"));

                // Receive the message from the server socket
                string m1;
                    byte[] buffer;
                if (server.TryReceiveFrameBytes(out buffer))
                {

                    m1 = System.Text.Encoding.UTF8.GetString(buffer);
                    Console.WriteLine("From Client: {0}", m1);
                }
                // Send a response back from the server
                server.SendFrame("Hi Back");

                // Receive the response from the client socket
                string m2 = client.ReceiveFrameString();
                Console.WriteLine("From Server: {0}", m2);
            }

**Comment by maikebing** [comment]
/22/17 4:51:46 PM Rep.XRecv - cannot receive another request   at NetMQ.Core.Patterns.Rep.XRecv(Msg& msg)
   at NetMQ.Core.SocketBase.TryRecv(Msg& msg, TimeSpan timeout)
   at NetMQ.NetMQSocket.TryReceive(Msg& msg, TimeSpan timeout)
   at NetMQ.ReceivingSocketExtensions.ReceiveFrameBytes(IReceivingSocket socket, Boolean& more)
   at MessageRouter.ZMQRouter.ZMQMsgRouter()

**Comment by somdoron** [comment]
I think the problem is that the message is not arrived yet, so you are getting false from TryReceive, you then try to receive. Try to use TryReceive with some timeout or move to inproc.

Regarding the exception, if you are using Response, you must send after each receive.
Try to use Router, Dealer instead.

**Comment by maikebing** [comment]
use ReceiveFrameBytes  , I can receive data! 
TryReceiveFrameBytes  can work at the .net 4.0 app!just my  dotnet core app  TryReceiveFrameBytes can't work!

**Comment by somdoron** [comment]
Just use TryReceive with timeout parameter.
It is timing, you are using TCP between the sockets, and Try* without timeout doesn't wait for a message, it exit immediately if there is no message waiting. In your case no message is waiting so the method return false.

The difference between v4 and dotnet core might be because v4 is faster, anyway it is just timing. Call with a timeout, or use a poller. with Try* you need to know that it might not get a message. If you want a message no matter what don't use the Try*

**Comment by maikebing** [comment]
Thanks! @somdoron
