### ISSUE TITLE
dealer socket missing messages

### ISSUE THREAD

**Issue by williamlee1982** [zeromq/netmq#675]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System:  windows 10
    .NET Version:     4.5.2

### Expected behaviour
dealer socket receive missing messages

### Actual behaviour
dealer socket can NOT receive missing messages

### Steps to reproduce the behaviour
router-dealer mode:
1. router sending messages to dealer by appending a frame of dealer's identify
2. dealer down (connection lost)
3. router keep sending several messages to dealer
3. restart dealer and reconnect to router by setting the same identity
4. dealer missed all the previous messages which sent by router during the down period

**Comment by ciottied** [comment]
AFAIK NetMQ/zMQ is not a reliable messaging system.
If you want reliability you have to implement it by yourself.
A quick and dirty solution, for short disconnection, may be to increase the highwatermark property of the router socket.

**Comment by williamlee1982** [comment]
i agree netmq is not reliable by default. the problem is, no matter what HWM i set, ALL messages sent from router during the dealer down period are lost. this seems not a expected behavior because a REQ-REP pattern would work well in the same situation

**Comment by ciottied** [comment]
Didn't know about this behavior for dealer-router, but It's what I would expect from plain old TCP sockets.
I use Pub-Sub for market data distribution and I had to implement "state management" with hearbeat and snapshots sent to Subs in case of disconnections.

**Comment by jabak** [comment]
According to the zeromq documentation router sockets silently discards messages when sending to peers that no longer exist.  NetMq is by design inherently unreliable. Reliability is sacrified for speed. That doesn't mean it's useless but it should be handled with care. 

One feature that would help a lot in that department is access to the send and receive queue, confggurable behaviour in case of connection loss(discard, block or send to deadletter) and some sort of optional deadletter queue hand in hand with a configurable retry strategy. With those features in place  one could easlily implement simple plumbing around netmq to make it a LOT more reliable.
