### ISSUE TITLE
Exceptions throw from Poll method when zmq loopback connections are forcibly closed

### ISSUE THREAD

**Issue by unclepaul84** [zeromq/netmq#691]
### Environment

    NetMQ Version:    3.3.3.4
    Operating System:  Windows Server 2012
    .NET Version:     4.6

### Description of  behavior
As far as we understand each zmq socket makes several loopback connections to itself. When those connections are closed unexpectedly, bad things happen.

### Steps to reproduce the behavior

Create a dealer/router socket process pair that uses socket polling. After they are connected, use TCPView to kill ALL connections related to those two processes, you should get error below. This error is unrecoverable. We run our processes on VMWare and those loopback connections sometimes get forcibly closed by something and this forces us restart our process.

Parameter name: All lists are either null or empty.
   at System.Net.Sockets.Socket.Select(IList checkRead, IList checkWrite, IList checkError, Int32 microSeconds)
   at NetMQ.Core.Utils.Selector.Select(SelectItem[] items, Int32 itemsCount, Int64 timeout)
   at NetMQ.NetMQSocket.Poll(PollEvents pollEvents, TimeSpan timeout)
   at NetMQ.NetMQSocket.Poll(TimeSpan timeout)

We can provide test driver if needed.

**Comment by unclepaul84** [comment]
Any thoughts on this?

**Comment by crosscode-nl** [comment]
I have the same issue. It happens with this implementation as well as the c++ ZeroMQ implementation. I also have this problem on windows with a customer using VMWare. 

Do you happen to know WHY VMWare closes localhost connections?

I'm considering to fork this or the C++ project to fix this myself, even if this cost performance, because as it stands right now this not usable.
