### ISSUE TITLE
HasOut is always true

### ISSUE THREAD

**Issue by BrannonKing** [zeromq/netmq#706]
### Environment

    NetMQ Version:    4.0.0.4
    Operating System: Windows 10, latest updates
    .NET Version:     .NET Core 2.0

### Expected behavior
RouterSocket.HasOut goes low/false when its send queue is empty.

### Actual behavior
HasOut is always high/true.
https://github.com/zeromq/netmq/issues/440 mentions that such is the case for "publishers".

What can I do to flush my sender? Or how can I wait for the send-queue to be empty?

**Comment by abeham** [comment]
I too stumbled upon this issue, currently the behaviour seems opposite of what is documented. In my case I used a RequestSocket instead of a RouterSocket, but the issue is the same. I looked a little bit into the source code:

In `Req.cs` the following code:

```csharp
protected override bool XHasOut()
{
    if (m_receivingReply && m_strict)
        return false;

    return base.XHasOut();
}
```

The base call goes to a `Dealer` which in turn forwards it to the `LoadBalancer` which has this implementation:

```csharp
public bool HasOut()
{
// If one part of the message was already written we can definitely
// write the rest of the message.
if (m_more)
    return true;

while (m_active > 0)
{

    // Check whether a pipe has room for another message.
    if (m_pipes[m_current].CheckWrite())
        return true;

    // Deactivate the pipe.
    m_active--;
    m_pipes.Swap(m_current, m_active);
    if (m_current == m_active)
        m_current = 0;
}

return false;
}
```

So, the issue here seems to be that `LoadBalancer` says HasOut() when there is _room for another message_, e.g., when a message has not been sent. I think the return should be true if _one_ of the pipes returns _false_ for CheckWrite.

But I'm not sure if it's as simple as replacing `if (m_pipes[m_current].CheckWrite())` with `if (!m_pipes[m_current].CheckWrite())`. Also, I don't know if this affects other code.

**Comment by amosialek** [comment]
I have replaced ([zeromq/clrzmq](https://github.com/zeromq/clrzmq) )
```
    int option;
    m_request.GetOption(ZSocketOption.EVENTS, out option);
    if ((option & (int) ZPoll.Out) == 0) break; // no room to send a message
```
with (netmq)
```
    if (m_request.HasOut) break; // no room to send a message
```
where m_request is `DealerSocket`
In previous version it returned `false` if there was room, now it does the opposite...
